# Generated by Django 4.2 on 2023-05-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarkTournirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournirs_time', models.TextField()),
                ('tournirs_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.category')),
            ],
        ),
        migrations.CreateModel(
            name='CyberiumTournirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournirs_time', models.TextField()),
                ('tournirs_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.category')),
            ],
        ),
        migrations.CreateModel(
            name='CyberArenaTournirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournirs_time', models.TextField()),
                ('tournirs_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.category')),
            ],
        ),
    ]
