# Generated by Django 4.2 on 2023-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_starktournirs_cyberiumtournirs_cyberarenatournirs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournirsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tournirs', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Категории Турниров',
            },
        ),
        migrations.AlterModelOptions(
            name='cyberarenatournirs',
            options={'verbose_name_plural': 'CyberArena'},
        ),
        migrations.AlterModelOptions(
            name='cyberiumtournirs',
            options={'verbose_name_plural': 'Cyberium'},
        ),
        migrations.AlterModelOptions(
            name='starktournirs',
            options={'verbose_name_plural': 'StarkGaming'},
        ),
    ]
